name: weapontest
version: 0.0.1
author: skippi
main: io.github.skippi.weapontest.WeaponTestPlugin
depend: [ProtocolLib]
website: https://github.com/skippi/weapontest
api-version: 1.16
commands:
  skilldebugmenu:
    description: Open skill debug menu.
    usage: /<command>
